# Generated by Django 2.2.5 on 2019-09-15 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('likes', models.IntegerField(default=0)),
                ('friends', models.IntegerField(default=0)),
                ('events', models.IntegerField(default=0)),
            ],
        ),
    ]
