# Generated by Django 2.2.5 on 2019-09-15 01:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='date',
            field=models.DateField(default=datetime.datetime(2019, 9, 14, 21, 8, 21, 968090)),
        ),
    ]
