# Generated by Django 2.2.5 on 2019-09-15 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_user_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='date',
            field=models.DateField(default=models.DateTimeField(auto_now_add=True)),
        ),
    ]
